name = "verifikasi-api"
main = "src/index.js"
compatibility_date = "2026-07-31"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "verifikasi.site/data*", zone_name = "verifikasi.site" },
  { pattern = "verifikasi.site/api/data*", zone_name = "verifikasi.site" }
]

[[kv_namespaces]]
binding = "DATA"
id = "1cabd6aa38c64e908dc453dcba3cd153"
